# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\poseviewerMainGui.ui'
#
# Created: Mon Dec 29 14:42:33 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 649)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.imageLabel = QtGui.QLabel(self.centralwidget)
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOptions = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptions.setIcon(icon)
        self.actionOptions.setObjectName("actionOptions")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon2)
        self.actionPause.setVisible(False)
        self.actionPause.setIconVisibleInMenu(True)
        self.actionPause.setObjectName("actionPause")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon3)
        self.actionPlay.setObjectName("actionPlay")
        self.actionFullscreen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFullscreen.setIcon(icon4)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon5)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon6)
        self.actionNext.setObjectName("actionNext")
        self.actionShuffle = QtGui.QAction(MainWindow)
        self.actionShuffle.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShuffle.setIcon(icon7)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionExitFullscreen = QtGui.QAction(MainWindow)
        self.actionExitFullscreen.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/closefullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExitFullscreen.setIcon(icon8)
        self.actionExitFullscreen.setVisible(False)
        self.actionExitFullscreen.setObjectName("actionExitFullscreen")
        self.actionSoundOn = QtGui.QAction(MainWindow)
        self.actionSoundOn.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/soundon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSoundOn.setIcon(icon9)
        self.actionSoundOn.setVisible(False)
        self.actionSoundOn.setObjectName("actionSoundOn")
        self.actionSoundOff = QtGui.QAction(MainWindow)
        self.actionSoundOff.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/soundoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSoundOff.setIcon(icon10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionSoundOff.setFont(font)
        self.actionSoundOff.setVisible(True)
        self.actionSoundOff.setObjectName("actionSoundOff")
        self.toolBar.addAction(self.actionOptions)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionFullscreen)
        self.toolBar.addAction(self.actionExitFullscreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShuffle)
        self.toolBar.addAction(self.actionSoundOn)
        self.toolBar.addAction(self.actionSoundOff)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Poseviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open (Ctrl+O)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setToolTip(QtGui.QApplication.translate("MainWindow", "Pause (space)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setToolTip(QtGui.QApplication.translate("MainWindow", "Play (space)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Fullscreen (F11)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous image (Left arrow)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next image (Right arrow)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShuffle.setText(QtGui.QApplication.translate("MainWindow", "Shuffle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShuffle.setToolTip(QtGui.QApplication.translate("MainWindow", "Shuffle order", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExitFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Exit Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExitFullscreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit from fullscreen mode.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExitFullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSoundOn.setText(QtGui.QApplication.translate("MainWindow", "Turn Sound On", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSoundOn.setToolTip(QtGui.QApplication.translate("MainWindow", "Turn on sound effects during slideshow.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSoundOff.setText(QtGui.QApplication.translate("MainWindow", "Turn Sound Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSoundOff.setToolTip(QtGui.QApplication.translate("MainWindow", "Turn off sound effects during slideshow.", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
