# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\poseviewerMainGui.ui'
#
# Created: Thu Jan 15 16:41:22 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 649)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/windowicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSpeed = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeed.setIcon(icon1)
        self.actionSpeed.setObjectName("actionSpeed")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon3)
        self.actionPlay.setObjectName("actionPlay")
        self.actionFullscreen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFullscreen.setIcon(icon4)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon5)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon6)
        self.actionNext.setObjectName("actionNext")
        self.actionShuffle = QtGui.QAction(MainWindow)
        self.actionShuffle.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShuffle.setIcon(icon7)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionSound = QtGui.QAction(MainWindow)
        self.actionSound.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/soundon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSound.setIcon(icon8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionSound.setFont(font)
        self.actionSound.setVisible(True)
        self.actionSound.setObjectName("actionSound")
        self.actionTimer = QtGui.QAction(MainWindow)
        self.actionTimer.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimer.setIcon(icon9)
        self.actionTimer.setObjectName("actionTimer")
        self.toolBar.addAction(self.actionSpeed)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionFullscreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShuffle)
        self.toolBar.addAction(self.actionSound)
        self.toolBar.addAction(self.actionTimer)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Poseviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpeed.setText(QtGui.QApplication.translate("MainWindow", "Change slideshow speed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpeed.setToolTip(QtGui.QApplication.translate("MainWindow", "Change slideshow speed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Directory (Ctrl+O)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Toggle slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle slideshow (space)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Toggle Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle Fullscreen (F11)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setText(QtGui.QApplication.translate("MainWindow", "Previous image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous image (Left arrow)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next image (Right arrow)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShuffle.setText(QtGui.QApplication.translate("MainWindow", "Shuffle images", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShuffle.setToolTip(QtGui.QApplication.translate("MainWindow", "Shuffle images", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSound.setText(QtGui.QApplication.translate("MainWindow", "Toggle sound effects during slideshow.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSound.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle sound effects during slideshow.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTimer.setText(QtGui.QApplication.translate("MainWindow", "Toggle timer display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTimer.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle timer display", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
