# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poseviewer\ui\slideshowsettingsui.ui'
#
# Created: Sat Sep 12 19:40:31 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(350, 240)
        Dialog.setMinimumSize(QtCore.QSize(350, 240))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.transition_speed_spinner = QtGui.QDoubleSpinBox(Dialog)
        self.transition_speed_spinner.setReadOnly(False)
        self.transition_speed_spinner.setSingleStep(0.5)
        self.transition_speed_spinner.setProperty("value", 1.0)
        self.transition_speed_spinner.setObjectName("transition_speed_spinner")
        self.gridLayout.addWidget(self.transition_speed_spinner, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.tab_widget = QtGui.QTabWidget(Dialog)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.speed_spinner = QtGui.QSpinBox(self.tab_1)
        self.speed_spinner.setFrame(True)
        self.speed_spinner.setMinimum(1)
        self.speed_spinner.setMaximum(999999999)
        self.speed_spinner.setSingleStep(5)
        self.speed_spinner.setProperty("value", 30)
        self.speed_spinner.setObjectName("speed_spinner")
        self.gridLayout_4.addWidget(self.speed_spinner, 0, 1, 1, 1)
        self.increment_checkbox = QtGui.QCheckBox(self.tab_1)
        self.increment_checkbox.setObjectName("increment_checkbox")
        self.gridLayout_4.addWidget(self.increment_checkbox, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_1)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.increment_interval_spinner = QtGui.QSpinBox(self.groupBox)
        self.increment_interval_spinner.setMinimum(1)
        self.increment_interval_spinner.setMaximum(999999999)
        self.increment_interval_spinner.setProperty("value", 5)
        self.increment_interval_spinner.setObjectName("increment_interval_spinner")
        self.gridLayout_2.addWidget(self.increment_interval_spinner, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.total_images_label = QtGui.QLabel(self.groupBox)
        self.total_images_label.setObjectName("total_images_label")
        self.gridLayout_2.addWidget(self.total_images_label, 2, 1, 1, 1)
        self.slideshow_time_left_label = QtGui.QLabel(self.groupBox)
        self.slideshow_time_left_label.setObjectName("slideshow_time_left_label")
        self.gridLayout_2.addWidget(self.slideshow_time_left_label, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 2)
        self.tab_widget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.total_time_edit = QtGui.QTimeEdit(self.tab_2)
        self.total_time_edit.setReadOnly(False)
        self.total_time_edit.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.total_time_edit.setSpecialValueText("")
        self.total_time_edit.setAccelerated(False)
        self.total_time_edit.setCurrentSection(QtGui.QDateTimeEdit.MinuteSection)
        self.total_time_edit.setCurrentSectionIndex(1)
        self.total_time_edit.setTime(QtCore.QTime(0, 20, 0))
        self.total_time_edit.setObjectName("total_time_edit")
        self.gridLayout_3.addWidget(self.total_time_edit, 0, 1, 1, 1)
        self.time_edit_table = TimeEditTable(self.tab_2)
        self.time_edit_table.setRowCount(3)
        self.time_edit_table.setColumnCount(2)
        self.time_edit_table.setObjectName("time_edit_table")
        self.time_edit_table.setColumnCount(2)
        self.time_edit_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.time_edit_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.time_edit_table.setHorizontalHeaderItem(1, item)
        self.time_edit_table.horizontalHeader().setVisible(False)
        self.time_edit_table.horizontalHeader().setCascadingSectionResizes(True)
        self.time_edit_table.horizontalHeader().setSortIndicatorShown(False)
        self.time_edit_table.horizontalHeader().setStretchLastSection(True)
        self.time_edit_table.verticalHeader().setVisible(False)
        self.time_edit_table.verticalHeader().setCascadingSectionResizes(True)
        self.time_edit_table.verticalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.time_edit_table, 1, 0, 1, 2)
        self.add_time_edit_table_row = QtGui.QPushButton(self.tab_2)
        self.add_time_edit_table_row.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_time_edit_table_row.setIcon(icon)
        self.add_time_edit_table_row.setObjectName("add_time_edit_table_row")
        self.gridLayout_3.addWidget(self.add_time_edit_table_row, 2, 0, 1, 1)
        self.remove_time_edit_table_row = QtGui.QPushButton(self.tab_2)
        self.remove_time_edit_table_row.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_time_edit_table_row.setIcon(icon1)
        self.remove_time_edit_table_row.setObjectName("remove_time_edit_table_row")
        self.gridLayout_3.addWidget(self.remove_time_edit_table_row, 2, 1, 1, 1)
        self.tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.add_value_table_row = QtGui.QPushButton(self.tab_3)
        self.add_value_table_row.setText("")
        self.add_value_table_row.setIcon(icon)
        self.add_value_table_row.setObjectName("add_value_table_row")
        self.gridLayout_6.addWidget(self.add_value_table_row, 2, 0, 1, 1)
        self.remove_value_table_row = QtGui.QPushButton(self.tab_3)
        self.remove_value_table_row.setText("")
        self.remove_value_table_row.setIcon(icon1)
        self.remove_value_table_row.setObjectName("remove_value_table_row")
        self.gridLayout_6.addWidget(self.remove_value_table_row, 2, 1, 1, 1)
        self.value_table = ValueTable(self.tab_3)
        self.value_table.setRowCount(3)
        self.value_table.setColumnCount(2)
        self.value_table.setObjectName("value_table")
        self.value_table.setColumnCount(2)
        self.value_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(1, item)
        self.value_table.horizontalHeader().setVisible(False)
        self.value_table.horizontalHeader().setCascadingSectionResizes(True)
        self.value_table.horizontalHeader().setSortIndicatorShown(False)
        self.value_table.horizontalHeader().setStretchLastSection(True)
        self.value_table.verticalHeader().setVisible(False)
        self.value_table.verticalHeader().setCascadingSectionResizes(True)
        self.value_table.verticalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.value_table, 1, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 3, 0, 1, 1)
        self.total_time_value_table = QtGui.QLabel(self.tab_3)
        self.total_time_value_table.setObjectName("total_time_value_table")
        self.gridLayout_6.addWidget(self.total_time_value_table, 3, 1, 1, 1)
        self.tab_widget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.increment_checkbox, QtCore.SIGNAL("toggled(bool)"), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.remove_time_edit_table_row, QtCore.SIGNAL("clicked()"), self.time_edit_table.remove_row)
        QtCore.QObject.connect(self.add_time_edit_table_row, QtCore.SIGNAL("clicked()"), self.time_edit_table.insert_row)
        QtCore.QObject.connect(self.add_value_table_row, QtCore.SIGNAL("clicked()"), self.value_table.insert_row)
        QtCore.QObject.connect(self.remove_value_table_row, QtCore.SIGNAL("clicked()"), self.value_table.remove_row)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tab_widget, self.transition_speed_spinner)
        Dialog.setTabOrder(self.transition_speed_spinner, self.add_time_edit_table_row)
        Dialog.setTabOrder(self.add_time_edit_table_row, self.speed_spinner)
        Dialog.setTabOrder(self.speed_spinner, self.increment_interval_spinner)
        Dialog.setTabOrder(self.increment_interval_spinner, self.increment_checkbox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Slideshow settings", None, QtGui.QApplication.UnicodeUTF8))
        self.transition_speed_spinner.setSuffix(QtGui.QApplication.translate("Dialog", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("Dialog", "The slideshow will transition for this amount of seconds before going to the next image.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Image transition speed: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Slideshow speed: ", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_spinner.setSuffix(QtGui.QApplication.translate("Dialog", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_checkbox.setText(QtGui.QApplication.translate("Dialog", "Increment slideshow speed?", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Increment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Slideshow time left: ", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_interval_spinner.setSuffix(QtGui.QApplication.translate("Dialog", " image(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Enter increment interval: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Total amount of images in slideshow:", None, QtGui.QApplication.UnicodeUTF8))
        self.total_images_label.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.slideshow_time_left_label.setText(QtGui.QApplication.translate("Dialog", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_1), QtGui.QApplication.translate("Dialog", "Preset 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Total time:", None, QtGui.QApplication.UnicodeUTF8))
        self.total_time_edit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "H:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.time_edit_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.time_edit_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.add_time_edit_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Add row", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_time_edit_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Remove row", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Preset 2", None, QtGui.QApplication.UnicodeUTF8))
        self.add_value_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Add row", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_value_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Remove row", None, QtGui.QApplication.UnicodeUTF8))
        self.value_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Number of images", None, QtGui.QApplication.UnicodeUTF8))
        self.value_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Total time:", None, QtGui.QApplication.UnicodeUTF8))
        self.total_time_value_table.setText(QtGui.QApplication.translate("Dialog", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Preset 3", None, QtGui.QApplication.UnicodeUTF8))

from ..tables import ValueTable, TimeEditTable
