# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poseviewer\ui\slideshowsettingsui.ui'
#
# Created: Tue Sep 29 19:49:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(380, 270)
        Dialog.setMinimumSize(QtCore.QSize(380, 270))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.settings_tabs = QtGui.QTabWidget(Dialog)
        self.settings_tabs.setObjectName("settings_tabs")
        self.slideshow_settings_tab = QtGui.QWidget()
        self.slideshow_settings_tab.setObjectName("slideshow_settings_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.slideshow_settings_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.preset_tabs = QtGui.QTabWidget(self.slideshow_settings_tab)
        self.preset_tabs.setObjectName("preset_tabs")
        self.tab_0 = QtGui.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtGui.QLabel(self.tab_0)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.base_speed_timeedit = QtGui.QTimeEdit(self.tab_0)
        self.base_speed_timeedit.setFrame(True)
        self.base_speed_timeedit.setTime(QtCore.QTime(0, 0, 30))
        self.base_speed_timeedit.setCurrentSection(QtGui.QDateTimeEdit.SecondSection)
        self.base_speed_timeedit.setObjectName("base_speed_timeedit")
        self.gridLayout_7.addWidget(self.base_speed_timeedit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_0)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 1, 0, 1, 1)
        self.transition_speed_spinner = QtGui.QDoubleSpinBox(self.tab_0)
        self.transition_speed_spinner.setReadOnly(False)
        self.transition_speed_spinner.setSingleStep(0.5)
        self.transition_speed_spinner.setProperty("value", 1.0)
        self.transition_speed_spinner.setObjectName("transition_speed_spinner")
        self.gridLayout_7.addWidget(self.transition_speed_spinner, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_0)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 0, 1, 1)
        self.preset_selector = QtGui.QComboBox(self.tab_0)
        self.preset_selector.setObjectName("preset_selector")
        self.preset_selector.addItem("")
        self.preset_selector.addItem("")
        self.preset_selector.addItem("")
        self.preset_selector.addItem("")
        self.gridLayout_7.addWidget(self.preset_selector, 2, 1, 1, 1)
        self.preset_tabs.addTab(self.tab_0, "")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.formLayout = QtGui.QFormLayout(self.tab_1)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtGui.QLabel(self.tab_1)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.increment_base_speed_label = QtGui.QLabel(self.tab_1)
        self.increment_base_speed_label.setObjectName("increment_base_speed_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.increment_base_speed_label)
        self.label_2 = QtGui.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.increment_interval_spinner = QtGui.QSpinBox(self.tab_1)
        self.increment_interval_spinner.setMinimum(1)
        self.increment_interval_spinner.setMaximum(999999999)
        self.increment_interval_spinner.setProperty("value", 5)
        self.increment_interval_spinner.setObjectName("increment_interval_spinner")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.increment_interval_spinner)
        self.label_5 = QtGui.QLabel(self.tab_1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.increment_time_left_label = QtGui.QLabel(self.tab_1)
        self.increment_time_left_label.setObjectName("increment_time_left_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.increment_time_left_label)
        self.label_4 = QtGui.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.increment_total_images_label = QtGui.QLabel(self.tab_1)
        self.increment_total_images_label.setObjectName("increment_total_images_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.increment_total_images_label)
        self.preset_tabs.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.total_random_time_edit = QtGui.QTimeEdit(self.tab_2)
        self.total_random_time_edit.setReadOnly(False)
        self.total_random_time_edit.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.total_random_time_edit.setSpecialValueText("")
        self.total_random_time_edit.setAccelerated(False)
        self.total_random_time_edit.setTime(QtCore.QTime(0, 20, 0))
        self.total_random_time_edit.setCurrentSection(QtGui.QDateTimeEdit.MinuteSection)
        self.total_random_time_edit.setCurrentSectionIndex(1)
        self.total_random_time_edit.setObjectName("total_random_time_edit")
        self.gridLayout_3.addWidget(self.total_random_time_edit, 0, 1, 1, 1)
        self.add_preset_2_table_row = QtGui.QPushButton(self.tab_2)
        self.add_preset_2_table_row.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_preset_2_table_row.setIcon(icon)
        self.add_preset_2_table_row.setObjectName("add_preset_2_table_row")
        self.gridLayout_3.addWidget(self.add_preset_2_table_row, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.remove_preset_2_table_row = QtGui.QPushButton(self.tab_2)
        self.remove_preset_2_table_row.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_preset_2_table_row.setIcon(icon1)
        self.remove_preset_2_table_row.setObjectName("remove_preset_2_table_row")
        self.gridLayout_3.addWidget(self.remove_preset_2_table_row, 2, 1, 1, 1)
        self.random_time_table = RandomTimeTable(self.tab_2)
        self.random_time_table.setRowCount(1)
        self.random_time_table.setObjectName("random_time_table")
        self.random_time_table.setColumnCount(1)
        self.random_time_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.random_time_table.setHorizontalHeaderItem(0, item)
        self.gridLayout_3.addWidget(self.random_time_table, 1, 0, 1, 2)
        self.preset_tabs.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.add_images_time_table_row = QtGui.QPushButton(self.tab_3)
        self.add_images_time_table_row.setText("")
        self.add_images_time_table_row.setIcon(icon)
        self.add_images_time_table_row.setObjectName("add_images_time_table_row")
        self.gridLayout_6.addWidget(self.add_images_time_table_row, 1, 0, 1, 1)
        self.remove_images_time_table_row = QtGui.QPushButton(self.tab_3)
        self.remove_images_time_table_row.setText("")
        self.remove_images_time_table_row.setIcon(icon1)
        self.remove_images_time_table_row.setObjectName("remove_images_time_table_row")
        self.gridLayout_6.addWidget(self.remove_images_time_table_row, 1, 1, 1, 1)
        self.images_total_time_label = QtGui.QLabel(self.tab_3)
        self.images_total_time_label.setObjectName("images_total_time_label")
        self.gridLayout_6.addWidget(self.images_total_time_label, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.images_time_table = ImagesTimeTable(self.tab_3)
        self.images_time_table.setRowCount(3)
        self.images_time_table.setObjectName("images_time_table")
        self.images_time_table.setColumnCount(2)
        self.images_time_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.images_time_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.images_time_table.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.images_time_table, 0, 0, 1, 2)
        self.preset_tabs.addTab(self.tab_3, "")
        self.gridLayout_5.addWidget(self.preset_tabs, 0, 1, 1, 1)
        self.settings_tabs.addTab(self.slideshow_settings_tab, "")
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.settings_tabs.addTab(self.settings_tab, "")
        self.gridLayout.addWidget(self.settings_tabs, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.settings_tabs.setCurrentIndex(0)
        self.preset_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.add_preset_2_table_row, QtCore.SIGNAL("clicked()"), self.random_time_table.insert_row)
        QtCore.QObject.connect(self.remove_preset_2_table_row, QtCore.SIGNAL("clicked()"), self.random_time_table.remove_row)
        QtCore.QObject.connect(self.add_images_time_table_row, QtCore.SIGNAL("clicked()"), self.images_time_table.insert_row)
        QtCore.QObject.connect(self.remove_images_time_table_row, QtCore.SIGNAL("clicked()"), self.images_time_table.remove_row)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Slideshow settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Slideshow speed: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("Dialog", "The slideshow will transition for this amount of seconds before going to the next image.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Image transition speed: ", None, QtGui.QApplication.UnicodeUTF8))
        self.transition_speed_spinner.setSuffix(QtGui.QApplication.translate("Dialog", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Use preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_selector.setItemText(0, QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_selector.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_selector.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_selector.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_tabs.setTabText(self.preset_tabs.indexOf(self.tab_0), QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Base speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_base_speed_label.setText(QtGui.QApplication.translate("Dialog", "0:00:30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Enter increment interval: ", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_interval_spinner.setSuffix(QtGui.QApplication.translate("Dialog", " image(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Slideshow time left: ", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_time_left_label.setText(QtGui.QApplication.translate("Dialog", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Total amount of images in slideshow:", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_total_images_label.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_tabs.setTabText(self.preset_tabs.indexOf(self.tab_1), QtGui.QApplication.translate("Dialog", "Preset 1", None, QtGui.QApplication.UnicodeUTF8))
        self.total_random_time_edit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "H:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.add_preset_2_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Add row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Total time:", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_preset_2_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Remove row", None, QtGui.QApplication.UnicodeUTF8))
        self.random_time_table.setToolTip(QtGui.QApplication.translate("Dialog", "Randomly picks inserted values for a duration of total time.", None, QtGui.QApplication.UnicodeUTF8))
        self.random_time_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_tabs.setTabText(self.preset_tabs.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Preset 2", None, QtGui.QApplication.UnicodeUTF8))
        self.add_images_time_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Add row", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_images_time_table_row.setToolTip(QtGui.QApplication.translate("Dialog", "Remove row", None, QtGui.QApplication.UnicodeUTF8))
        self.images_total_time_label.setText(QtGui.QApplication.translate("Dialog", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Total time:", None, QtGui.QApplication.UnicodeUTF8))
        self.images_time_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Number of images", None, QtGui.QApplication.UnicodeUTF8))
        self.images_time_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_tabs.setTabText(self.preset_tabs.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Preset 3", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.slideshow_settings_tab), QtGui.QApplication.translate("Dialog", "Slideshow Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.settings_tab), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))

from ..tables import RandomTimeTable, ImagesTimeTable
